### ISSUE TITLE
Animation Problem

### ISSUE THREAD

**Issue by EyuphanMandiraci** [vberlier/animated-models#1]
[https://hizliresim.com/26xSV9](url) <-- image link

what can I do?

animation is errored.

**Comment by vberlier** [comment]
If you want to use a block model you need to export the animation by overwriting a transparent block like glass otherwise all the transparent layers are displayed as solid black. The other option is to display the model by putting it on an armorstand's head.

**Comment by EyuphanMandiraci** [comment]
> If you want to use a block model you need to export the animation by overwriting a transparent block like glass otherwise all the transparent layers are displayed as solid black. The other option is to display the model by putting it on an armorstand's head.

thank you
